// Datos de ejemplo para el carrito de compras

export const mockCartItems = [
  {
    id: 1,
    name: "Smartphone Samsung Galaxy S21 128GB",
    brand: "Samsung",
    price: 699990,
    quantity: 1,
    image: "/products/samsung-s21.jpg",
    stock: 15,
    discount: 10,
    seller: "Samsung Official Store",
    variant: "Negro",
  },
  {
    id: 2,
    name: 'Notebook Lenovo ThinkPad X1 Carbon 14" Intel Core i7 16GB RAM 512GB SSD',
    brand: "Lenovo",
    price: 1299990,
    quantity: 1,
    image: "/products/lenovo-thinkpad.jpg",
    stock: 5,
    discount: 0,
    seller: "Lenovo Chile",
    variant: "Gris",
  },
  {
    id: 3,
    name: "Audífonos Inalámbricos Sony WH-1000XM4 con Noise Cancelling",
    brand: "Sony",
    price: 299990,
    quantity: 2,
    image: "/products/sony-headphones.jpg",
    stock: 8,
    discount: 15,
    seller: "Sony Store",
    variant: "Negro",
  },
]

export const mockRecommendedProducts = [
  {
    id: 101,
    name: "Apple AirPods Pro con Cancelación de Ruido",
    brand: "Apple",
    price: 249990,
    image: "/products/airpods-pro.jpg",
    discount: 5,
    rating: 4.8,
  },
  {
    id: 102,
    name: 'Monitor Samsung Odyssey G7 32" Curvo 240Hz Gaming',
    brand: "Samsung",
    price: 599990,
    image: "/products/samsung-monitor.jpg",
    discount: 0,
    rating: 4.7,
  },
  {
    id: 103,
    name: "Teclado Mecánico Logitech G Pro X RGB",
    brand: "Logitech",
    price: 129990,
    image: "/products/logitech-keyboard.jpg",
    discount: 10,
    rating: 4.6,
  },
  {
    id: 104,
    name: "Cámara Mirrorless Sony Alpha A7 III",
    brand: "Sony",
    price: 1799990,
    image: "/products/sony-camera.jpg",
    discount: 0,
    rating: 4.9,
  },
]
