// Mock product data
export const mockProduct = {
  id: 1,
  name: "Smartphone XYZ Ultra Pro 128GB",
  description:
    "El nuevo Smartphone XYZ Ultra Pro con 128GB de almacenamiento, 8GB de RAM, pantalla AMOLED de 6.5 pulgadas y cámara de 108MP. Experimenta el rendimiento más potente con el nuevo procesador Snapdragon 8 Gen 2.",
  price: 12999,
  originalPrice: 14999,
  rating: "4.8",
  reviews: 245,
  images: [
    "/placeholder.svg?height=500&width=500",
    "/placeholder.svg?height=500&width=500",
    "/placeholder.svg?height=500&width=500",
    "/placeholder.svg?height=500&width=500",
  ],
  freeShipping: true,
  stock: 15,
  seller: {
    name: "TechStore",
    rating: 4.9,
    sales: 1245,
  },
  category: "Electrónicos",
  subcategory: "Smartphones",
  features: [
    'Pantalla AMOLED 6.5"',
    "Procesador Snapdragon 8 Gen 2",
    "8GB RAM / 128GB Almacenamiento",
    "Cámara principal 108MP",
    "Batería 5000mAh",
    "Android 13",
    "5G",
  ],
  specifications: {
    Marca: "XYZ",
    Modelo: "Ultra Pro",
    "Sistema Operativo": "Android 13",
    "Tamaño de pantalla": "6.5 pulgadas",
    Resolución: "2400 x 1080 px",
    Procesador: "Snapdragon 8 Gen 2",
    "Memoria RAM": "8GB",
    Almacenamiento: "128GB",
    "Cámara principal": "108MP + 12MP + 8MP",
    "Cámara frontal": "32MP",
    Batería: "5000mAh",
    Dimensiones: "160.1 x 74.8 x 8.6 mm",
    Peso: "196g",
  },
  colors: ["Negro", "Azul", "Plata"],
  warranty: "12 meses de garantía oficial",
}
